name: Node.js CI/CD with SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build and test
        run: npm test -- --coverage

      - name: Verify coverage
        run: |
          if [ ! -f "coverage/lcov.info" ]; then
            echo "Error: coverage file not found!"
            exit 1
          fi
          echo "Coverage file exists"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=ddaryb
            -Dsonar.projectKey=ddaryb_my-js-project
            -Dsonar.projectName=my-js-project
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**
            -Dsonar.coverage.exclusions=**/test/**,**/mock/**
            -Dsonar.ci.enabled=true
            -Dsonar.ci.autoconfig.disabled=true
            -Dsonar.scm.provider=git
            -Dsonar.sourceEncoding=UTF-8
            -X

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: |
            coverage/
            .scannerwork/
          retention-days: 3